version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: xclau_db
    environment:
      MYSQL_DATABASE: xclau # Nombre de la base de datos
      MYSQL_ROOT_PASSWORD: secret # Contrase침a del root (simple para desarrollo)
      MYSQL_USER: xclau_user # Usuario est치ndar (opcional)
      MYSQL_PASSWORD: secret # Contrase침a del usuario est치ndar
    volumes:
      - db_data:/var/lib/mysql # Volumen para persistir datos de la BD
    ports:
      - "3306:3306" # Exponer MySQL en el puerto 3306 host (acceso desde host/DBeaver)
    restart: always

  backend:
    image: php:8.2-apache
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xclau_backend
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
      - ./backend/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./frontend/public/build:/var/www/html/public/build
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=xclau
      - DB_USERNAME=xclau_user
      - DB_PASSWORD=secret
      - APP_URL=http://localhost:8000
      - SANCTUM_STATEFUL_DOMAINS=localhost:3000
      - SESSION_DOMAIN=localhost

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xclau_frontend
    working_dir: /app
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

volumes:
  db_data:
