version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
       MYSQL_DATABASE: xclau # Nombre de la base de datos
       MYSQL_ROOT_PASSWORD: secret # Contrase침a del root (simple para desarrollo)
       MYSQL_USER: xclau_user # Usuario est치ndar (opcional)
       MYSQL_PASSWORD: secret # Contrase침a del usuario est치ndar
    ports:
      - "3306:3306" # Exponer MySQL en el puerto 3306 host (acceso desde host/DBeaver)
    container_name: xclau_db
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      retries: 5
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
    env_file:
      - ./.env
    container_name: xclau_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - appnet
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: xclau_frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge